name: Ruff Formatter Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Ruff
        run: pip install ruff

      - name: Check formatting with Ruff
        run: ruff format --check --diff .
